// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7sCtOoiX8DA2Sf1zE19iF4k5WAxySQc',
    appId: '1:1026741882339:android:29c8eda5e01b350bd324d6',
    messagingSenderId: '1026741882339',
    projectId: 'volco-5ea01',
    storageBucket: 'volco-5ea01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcVJJ16aL1CZcmTKL8_bXMwLyF42fQ9I',
    appId: '1:1026741882339:ios:71de888a67d65a6fd324d6',
    messagingSenderId: '1026741882339',
    projectId: 'volco-5ea01',
    storageBucket: 'volco-5ea01.firebasestorage.app',
    iosBundleId: 'com.example.volco',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPCqNoB3E3GZKMJMlY0JgsnjTmzba5ag',
    appId: '1:1026741882339:web:4054bae596f726eed324d6',
    messagingSenderId: '1026741882339',
    projectId: 'volco-5ea01',
    authDomain: 'volco-5ea01.firebaseapp.com',
    storageBucket: 'volco-5ea01.firebasestorage.app',
    measurementId: 'G-0KYKGEQKPS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIcVJJ16aL1CZcmTKL8_bXMwLyF42fQ9I',
    appId: '1:1026741882339:ios:71de888a67d65a6fd324d6',
    messagingSenderId: '1026741882339',
    projectId: 'volco-5ea01',
    storageBucket: 'volco-5ea01.firebasestorage.app',
    iosBundleId: 'com.example.volco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiPCqNoB3E3GZKMJMlY0JgsnjTmzba5ag',
    appId: '1:1026741882339:web:165e89f78dc5e6b5d324d6',
    messagingSenderId: '1026741882339',
    projectId: 'volco-5ea01',
    authDomain: 'volco-5ea01.firebaseapp.com',
    storageBucket: 'volco-5ea01.firebasestorage.app',
    measurementId: 'G-275LLD187Z',
  );

}