import 'package:flutter/material.dart';
import 'package:volco/theme/custom_text_style.dart';
import 'package:volco/theme/theme_helper.dart';

class Themestylecheck extends StatelessWidget {
  const Themestylecheck({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Colors Section
            Text('Colors', style: CustomTextStyles.headlineLargePrimary),
            SizedBox(height: 16),
            Text('amber500', style: TextStyle(color: appTheme.amber500)),
            Text('black900', style: TextStyle(color: appTheme.black900)),
            Text('black90001', style: TextStyle(color: appTheme.black90001)),
            Text('black9000c', style: TextStyle(color: appTheme.black9000c)),
            Text('blueA200', style: TextStyle(color: appTheme.blueA200)),
            Text('blueA400', style: TextStyle(color: appTheme.blueA400)),
            Text('blueGray100', style: TextStyle(color: appTheme.blueGray100)),
            Text('blueGray900', style: TextStyle(color: appTheme.blueGray900)),
            Text('blueGray90059',
                style: TextStyle(color: appTheme.blueGray90059)),
            Text('blueGray90076',
                style: TextStyle(color: appTheme.blueGray90076)),
            Text('cyan200', style: TextStyle(color: appTheme.cyan200)),
            Text('cyan300', style: TextStyle(color: appTheme.cyan300)),
            Text('cyan500', style: TextStyle(color: appTheme.cyan500)),
            Text('cyan600', style: TextStyle(color: appTheme.cyan600)),
            Text('cyan900', style: TextStyle(color: appTheme.cyan900)),
            Text('gray400', style: TextStyle(color: appTheme.gray400)),
            Text('gray40001', style: TextStyle(color: appTheme.gray40001)),
            Text('gray50', style: TextStyle(color: appTheme.gray50)),
            Text('gray500', style: TextStyle(color: appTheme.gray500)),
            Text('gray5001', style: TextStyle(color: appTheme.gray5001)),
            Text('gray700', style: TextStyle(color: appTheme.gray700)),
            Text('gray800', style: TextStyle(color: appTheme.gray800)),
            Text('gray80000', style: TextStyle(color: appTheme.gray80000)),
            Text('gray80046', style: TextStyle(color: appTheme.gray80046)),
            Text('gray900', style: TextStyle(color: appTheme.gray900)),
            Text('gray8001d', style: TextStyle(color: appTheme.gray8001d)),
            Text('gray8002d', style: TextStyle(color: appTheme.gray8002d)),
            Text('green600', style: TextStyle(color: appTheme.green600)),
            Text('green60019', style: TextStyle(color: appTheme.green60019)),
            Text('greenA7003f', style: TextStyle(color: appTheme.greenA7003f)),
            Text('indigo900', style: TextStyle(color: appTheme.indigo900)),
            Text('indigoA20014',
                style: TextStyle(color: appTheme.indigoA20014)),
            Text('lightBlue600',
                style: TextStyle(color: appTheme.lightBlue600)),
            Text('red400', style: TextStyle(color: appTheme.red400)),
            Text('red40019', style: TextStyle(color: appTheme.red40019)),
            Text('red500', style: TextStyle(color: appTheme.red500)),
            Text('teal900', style: TextStyle(color: appTheme.teal900)),
            Text('whiteA700', style: TextStyle(color: appTheme.whiteA700)),
            Text('yellowA700', style: TextStyle(color: appTheme.yellowA700)),
            SizedBox(height: 32),

            // Text Styles Section
            Text('Text Styles', style: CustomTextStyles.headlineLargePrimary),
            SizedBox(height: 16),

            // Body Text Styles
            Text("bodyLarge16", style: CustomTextStyles.bodyLarge16),
            Text("bodyLarge16_1", style: CustomTextStyles.bodyLarge16_1),
            Text("bodyLargeGray40001",
                style: CustomTextStyles.bodyLargeGray40001),
            Text("bodyLargePrimary", style: CustomTextStyles.bodyLargePrimary),
            Text("bodyMediumBluegray100",
                style: CustomTextStyles.bodyMediumBluegray100),
            Text("bodyMediumGray40001",
                style: CustomTextStyles.bodyMediumGray40001),
            Text("bodyMediumGray50", style: CustomTextStyles.bodyMediumGray50),
            Text("bodyMediumGray500",
                style: CustomTextStyles.bodyMediumGray500),
            Text("bodyMediumWhiteA700",
                style: CustomTextStyles.bodyMediumWhiteA700),
            Text("bodySmall10", style: CustomTextStyles.bodySmall10),
            Text("bodySmall_1", style: CustomTextStyles.bodySmall_1),

            // Headline Text Styles
            Text("headlineLargePrimary",
                style: CustomTextStyles.headlineLargePrimary),
            Text("headlineSmallPrimary",
                style: CustomTextStyles.headlineSmallPrimary),
            Text("headlineSmallRed400",
                style: CustomTextStyles.headlineSmallRed400),

            // Label Text Styles
            Text("labelLargeGray40001",
                style: CustomTextStyles.labelLargeGray40001),
            Text("labelLargeWhiteA700",
                style: CustomTextStyles.labelLargeWhiteA700),
            Text("labelMediumBluegray100",
                style: CustomTextStyles.labelMediumBluegray100),
            Text("labelMediumCyan200",
                style: CustomTextStyles.labelMediumCyan200),
            Text("labelMediumCyan300",
                style: CustomTextStyles.labelMediumCyan300),
            Text("labelMediumPrimary",
                style: CustomTextStyles.labelMediumPrimary),
            Text("labelMediumPrimaryBold",
                style: CustomTextStyles.labelMediumPrimaryBold),
            Text("labelMediumRed400",
                style: CustomTextStyles.labelMediumRed400),
            Text("labelMediumRed400_1",
                style: CustomTextStyles.labelMediumRed400_1),

            // Title Text Styles
            Text("titleLarge20", style: CustomTextStyles.titleLarge20),
            Text("titleLargePrimary",
                style: CustomTextStyles.titleLargePrimary),
            Text("titleLargeSemiBold",
                style: CustomTextStyles.titleLargeSemiBold),
            Text("titleMedium16", style: CustomTextStyles.titleMedium16),
            Text("titleMedium16_1", style: CustomTextStyles.titleMedium16_1),
            Text("titleMediumGray40001",
                style: CustomTextStyles.titleMediumGray40001),
            Text("titleMediumGray50",
                style: CustomTextStyles.titleMediumGray50),
            Text("titleMediumOnPrimaryContainer",
                style: CustomTextStyles.titleMediumOnPrimaryContainer),
            Text("titleMediumPrimary",
                style: CustomTextStyles.titleMediumPrimary),
            Text("titleMediumPrimary16",
                style: CustomTextStyles.titleMediumPrimary16),
            Text("titleMediumPrimarySemiBold",
                style: CustomTextStyles.titleMediumPrimarySemiBold),
            Text("titleMediumPrimary_1",
                style: CustomTextStyles.titleMediumPrimary_1),
            Text("titleMediumRed400",
                style: CustomTextStyles.titleMediumRed400),
            Text("titleMediumSemiBold",
                style: CustomTextStyles.titleMediumSemiBold),
            Text("titleMediumSemiBold16",
                style: CustomTextStyles.titleMediumSemiBold16),
            Text("titleMediumSemiBold_1",
                style: CustomTextStyles.titleMediumSemiBold_1),
            Text("titleMediumSourceSansPro",
                style: CustomTextStyles.titleMediumSourceSansPro),
            Text("titleSmallGray400",
                style: CustomTextStyles.titleSmallGray400),
            Text("titleSmallGray40001",
                style: CustomTextStyles.titleSmallGray40001),
            Text("titleSmallPrimary",
                style: CustomTextStyles.titleSmallPrimary),
            Text("titleSmall_1", style: CustomTextStyles.titleSmall_1),
          ],
        ),
      ),
    ));
  }
}
